# -*- coding: utf-8 -*-

'''

Playlist generated by retroarch at lakka.tv:

{
  "version": "1.2",
  "default_core_path": "",
  "default_core_name": "",
  "label_display_mode": 0,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "items": [
    {
      "path": "/storage/roms/Sega - Mega Drive - Genesis/Comix Zone (USA).zip#Comix Zone (USA).md",
      "label": "Comix Zone (USA)",
      "core_path": "DETECT",
      "core_name": "DETECT",
      "crc32": "17DA0354|crc",
      "db_name": "Sega - Mega Drive - Genesis.lpl"
    }
  ]
}


'''

import requests
import json
import os
from zipfile import ZipFile

#rom_set = 'Sega - Mega Drive - Genesis'
#rom_set = 'Nintendo - Nintendo Entertainment System'
rom_set = 'Nintendo - Super Nintendo Entertainment System'

#rom_extension = ".md"
#rom_extension = ".nes"
rom_extension = ".sfc"

files_dir = '../../Downloads/roms/' + rom_set + '/'
storage_files_dir = '/storage/roms/' + rom_set + '/'
lpl_name = rom_set + '.lpl'

list_files = os.listdir(files_dir)

output = {}
output['version'] = "1.2"
output['default_core_path'] = ""
output['default_core_name'] = ""
output['label_display_mode'] = 0
output['right_thumbnail_mode'] = 0
output['left_thumbnail_mode'] = 0
output['items'] = []

for file in list_files:
    if ( file.find('.zip') > 0 ) and ( file.find('[BIOS]') == -1 ):
        item = {}
        rom_file = file.strip('.zip') + rom_extension
        label = file.strip('.zip')
        with ZipFile(files_dir + file, 'r') as zip:
                for info in zip.infolist():
                    if info.filename == rom_file:
                        item['path'] = storage_files_dir + file + "#" + rom_file
                        item['label'] = label
                        item['core_path'] = 'DETECT'
                        item['core_name'] = 'DETECT'
                        item['crc32'] = str(hex(info.CRC)).strip('0x').upper() + "|crc"
                        item['db_name'] = lpl_name
                        output['items'].append(item)

print(json.dumps(output, indent=4))
